#cloud-config
package_upgrade: true
package_update: true
packages:
  - docker.io
  - htop
  - git
  - python3-pip
  - python-is-python3
timezone: "Europe/Stockholm"
bootcmd:
  - echo bootcmd started at $(date)
  - echo $INSTANCE_ID > /etc/instance_id
  - apt-get install -y zsh
groups:
  - infosec: [ubuntu]
users:
  - name: ubuntu
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJu2T+SI/P2Aod5a8WNV1GLUQbhVhNKahiJxJ1+n0y8DPOyPQBcMNK31xkoCAUUx3IKZKqWIGraWVC/z3NqJPQb1YrmXtcXB37JioVPolr+yTh/aA4ka+YpdpBA9WlTjOXuqqT68kg/Dn9mhqylmIe9+WSsGjxzpsSqDaXsXPViUFVzIyW3cuG+DFie2E8E6NBiPUW8VSWxSU3h8ywIhMZMx0Sdr2cMqs6UY9WSlWRhXQkqHJRGSP9ZZX300c27s8f4UakJxMa1MZAHEvqEyuXuTPJa36KdIBolG0PBIUTXiGYQ3VUzSYC1ueRpDvQEQSf+uO12snCv9t0evwiIEC9PUcVcOwLMRM+fixMromgylTurvO2A2VMLZWccltykjLtv7FEqFx9T70wJzbVNPpGHxdvDJ9uz+DgCBwcSTjza1Mv4XmRM2rjhuCd8KTOcHwti7/rrGgSbPp7hw6u9p6DSdQ35Pz6C7wBU/Fgb0oM5SL8QVWXO95myEPDhlJzbfE= oem@prai
fqdn: patrick-c3-2

runcmd:
  - git config --global user.name "rai-prashanna"
  - git config --global user.email "prai931024@gmail.com"
  - python3 -m pip install -U "ray[default]"
  - python3 -m pip install -U jupyter
